-- Business Column Metadata Population Script
-- Populates detailed column-level business metadata for all relevant gaming tables

PRINT '=== POPULATING BUSINESS COLUMN METADATA ===';
PRINT 'Adding detailed column-level business context for intelligent BI queries';
PRINT '';

-- =====================================================
-- 1. tbl_Daily_actions - CORE TABLE Column Metadata
-- =====================================================

PRINT 'Populating column metadata for tbl_Daily_actions (CORE TABLE)...';

-- Get the TableInfoId for tbl_Daily_actions
DECLARE @DailyActionsTableId BIGINT;
SELECT @DailyActionsTableId = Id FROM BusinessTableInfo WHERE SchemaName = 'common' AND TableName = 'tbl_Daily_actions';

-- Insert column metadata for key financial columns
INSERT INTO BusinessColumnInfo (
    TableInfoId, ColumnName, BusinessMeaning, BusinessContext, DataExamples, ValidationRules, IsKeyColumn, 
    NaturalLanguageAliases, ValueExamples, DataLineage, CalculationRules, SemanticTags, BusinessDataType, 
    ConstraintsAndRules, DataQualityScore, UsageFrequency, PreferredAggregation, RelatedBusinessTerms, 
    IsSensitiveData, IsCalculatedField, CreatedBy, CreatedDate
) VALUES
-- Primary Keys and Identifiers
(@DailyActionsTableId, 'ID', 'Unique identifier for each daily action record', 'Primary key ensuring each daily summary record is uniquely identified', '1, 2, 3, 1000000', 'Must be unique, auto-incrementing', 1, '["Record ID", "Daily Action ID", "Primary Key"]', '["1", "2", "1000000"]', 'Auto-generated by database', 'IDENTITY(1,1)', '["primary_key", "identifier"]', 'Unique Identifier', 'NOT NULL, IDENTITY', 1.0, 0.3, 'COUNT', '["Primary Key"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'Date', 'Date of the daily activity summary', 'Critical dimension for time-based analysis and reporting. All financial metrics are aggregated by this date.', '2024-01-15, 2024-12-31', 'Must be valid date, typically current or past dates', 1, '["Activity Date", "Summary Date", "Report Date"]', '["2024-01-15", "2024-12-31"]', 'Source system transaction dates', 'Aggregated daily from transaction timestamps', '["date", "time_dimension", "critical"]', 'Date', 'NOT NULL', 1.0, 0.95, 'GROUP BY', '["Date", "Time Period"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'PlayerID', 'Unique identifier for each player across all brands', 'Links to player profile data. Essential for customer analytics and personalization.', '12345, 67890, 999999', 'Must exist in player master table', 1, '["Player", "Customer ID", "User ID"]', '["12345", "67890", "999999"]', 'Player registration system', 'Assigned at player registration', '["player_id", "customer", "foreign_key"]', 'Player Identifier', 'NOT NULL, Foreign Key', 1.0, 0.9, 'GROUP BY', '["Player ID", "Customer"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'WhiteLabelID', 'Brand/casino identifier for multi-brand operations', 'Identifies which casino brand the activity occurred on. Critical for brand-specific reporting.', '1, 2, 5, 10', 'Must exist in white labels table', 1, '["Brand ID", "Casino ID", "Label ID"]', '["1", "2", "5"]', 'Brand configuration system', 'Assigned based on player login brand', '["brand", "white_label", "foreign_key"]', 'Brand Identifier', 'Foreign Key', 0.95, 0.7, 'GROUP BY', '["White Label", "Brand"]', 0, 0, 'System', GETUTCDATE()),

-- Financial Metrics - Deposits
(@DailyActionsTableId, 'Deposits', 'Total deposit amount for the day', 'Sum of all successful deposits made by the player on this date. Key revenue metric.', '100.00, 500.50, 0.00', 'Must be >= 0, in base currency', 0, '["Total Deposits", "Deposit Amount", "Money In"]', '["100.00", "500.50", "0.00"]', 'Payment processing system', 'SUM of successful deposit transactions', '["deposit", "revenue", "financial", "money"]', 'Currency Amount', '>= 0', 0.98, 0.8, 'SUM', '["Deposits", "Revenue"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'PaidCashouts', 'Total withdrawal amount paid out', 'Sum of all successful withdrawals paid to the player. Reduces net revenue.', '50.00, 200.00, 0.00', 'Must be >= 0, in base currency', 0, '["Withdrawals", "Cashouts", "Money Out"]', '["50.00", "200.00", "0.00"]', 'Payment processing system', 'SUM of successful withdrawal transactions', '["withdrawal", "cashout", "financial", "money"]', 'Currency Amount', '>= 0', 0.98, 0.7, 'SUM', '["Withdrawals", "Cashouts"]', 0, 0, 'System', GETUTCDATE()),

-- Gaming Metrics - Bets and Wins
(@DailyActionsTableId, 'BetsReal', 'Total real money bets placed', 'Sum of all real money wagers placed by the player. Used for GGR calculation.', '250.00, 1000.00, 0.00', 'Must be >= 0, in base currency', 0, '["Real Bets", "Real Money Wagers", "Stakes"]', '["250.00", "1000.00", "0.00"]', 'Gaming platform transactions', 'SUM of real money bet amounts', '["bet", "wager", "gaming", "real_money"]', 'Currency Amount', '>= 0', 0.99, 0.9, 'SUM', '["Bets", "Wagers", "GGR"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'WinsReal', 'Total real money wins paid', 'Sum of all real money winnings paid to the player. Used for GGR calculation.', '180.00, 750.00, 0.00', 'Must be >= 0, in base currency', 0, '["Real Wins", "Real Money Winnings", "Payouts"]', '["180.00", "750.00", "0.00"]', 'Gaming platform transactions', 'SUM of real money win amounts', '["win", "payout", "gaming", "real_money"]', 'Currency Amount', '>= 0', 0.99, 0.9, 'SUM', '["Wins", "Payouts", "GGR"]', 0, 0, 'System', GETUTCDATE()),

-- Bonus Metrics
(@DailyActionsTableId, 'Bonuses', 'Total bonus amounts awarded', 'Sum of all bonuses credited to the player. Marketing cost that reduces NGR.', '25.00, 100.00, 0.00', 'Must be >= 0, in base currency', 0, '["Bonus Amount", "Promotional Credits", "Marketing Cost"]', '["25.00", "100.00", "0.00"]', 'Bonus management system', 'SUM of bonus credit amounts', '["bonus", "promotion", "marketing", "cost"]', 'Currency Amount', '>= 0', 0.95, 0.6, 'SUM', '["Bonuses", "Promotions", "NGR"]', 0, 0, 'System', GETUTCDATE()),

-- Vertical-Specific Metrics
(@DailyActionsTableId, 'BetsCasino', 'Casino games bet amount', 'Total bets placed on casino games (slots, table games, etc.)', '150.00, 800.00, 0.00', 'Must be >= 0, subset of total bets', 0, '["Casino Bets", "Casino Wagers", "Casino Stakes"]', '["150.00", "800.00", "0.00"]', 'Casino gaming platform', 'SUM of casino game bet amounts', '["casino", "bet", "gaming_vertical"]', 'Currency Amount', '>= 0', 0.98, 0.8, 'SUM', '["Casino Bets", "Gaming Vertical"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'BetsSport', 'Sports betting wager amount', 'Total bets placed on sports events and markets', '100.00, 500.00, 0.00', 'Must be >= 0, subset of total bets', 0, '["Sports Bets", "Sports Wagers", "Sportsbook Stakes"]', '["100.00", "500.00", "0.00"]', 'Sportsbook platform', 'SUM of sports bet amounts', '["sports", "bet", "gaming_vertical"]', 'Currency Amount', '>= 0', 0.98, 0.7, 'SUM', '["Sports Bets", "Sportsbook"]', 0, 0, 'System', GETUTCDATE()),

-- Player Lifecycle Indicators
(@DailyActionsTableId, 'Registration', 'New player registration indicator', 'Binary flag indicating if player registered on this date. Key for acquisition tracking.', '0, 1', 'Must be 0 or 1', 0, '["New Registration", "Player Acquisition", "Sign Up"]', '["0", "1"]', 'Player registration system', 'Set to 1 on registration date', '["registration", "acquisition", "lifecycle"]', 'Boolean Flag', 'BIT (0 or 1)', 1.0, 0.3, 'SUM', '["Registration", "Acquisition"]', 0, 0, 'System', GETUTCDATE()),

(@DailyActionsTableId, 'FTD', 'First Time Deposit indicator', 'Binary flag indicating if this was players first deposit. Critical acquisition metric.', '0, 1', 'Must be 0 or 1', 0, '["First Deposit", "FTD", "Conversion"]', '["0", "1"]', 'Payment processing system', 'Set to 1 on first successful deposit', '["ftd", "conversion", "acquisition"]', 'Boolean Flag', 'BIT (0 or 1)', 1.0, 0.4, 'SUM', '["FTD", "First Deposit", "Conversion"]', 0, 0, 'System', GETUTCDATE());

PRINT '✅ tbl_Daily_actions column metadata populated (12 key columns)';

-- =====================================================
-- 2. tbl_Daily_actions_players - Player Profile Columns
-- =====================================================

PRINT 'Populating column metadata for tbl_Daily_actions_players...';

-- Get the TableInfoId for tbl_Daily_actions_players
DECLARE @PlayersTableId BIGINT;
SELECT @PlayersTableId = Id FROM BusinessTableInfo WHERE SchemaName = 'common' AND TableName = 'tbl_Daily_actions_players';

INSERT INTO BusinessColumnInfo (
    TableInfoId, ColumnName, BusinessMeaning, BusinessContext, DataExamples, ValidationRules, IsKeyColumn, 
    NaturalLanguageAliases, ValueExamples, DataLineage, CalculationRules, SemanticTags, BusinessDataType, 
    ConstraintsAndRules, DataQualityScore, UsageFrequency, PreferredAggregation, RelatedBusinessTerms, 
    IsSensitiveData, IsCalculatedField, CreatedBy, CreatedDate
) VALUES
-- Player Identity
(@PlayersTableId, 'PlayerID', 'Unique player identifier', 'Primary key linking to all player activities and transactions', '12345, 67890, 999999', 'Must be unique across platform', 1, '["Player", "Customer ID", "User ID"]', '["12345", "67890"]', 'Player registration system', 'Auto-generated at registration', '["player_id", "primary_key"]', 'Player Identifier', 'NOT NULL, PRIMARY KEY', 1.0, 0.9, 'COUNT', '["Player ID"]', 0, 0, 'System', GETUTCDATE()),

(@PlayersTableId, 'Email', 'Player email address', 'Primary contact method and login credential. Critical for customer communication.', 'player@example.com, user123@gmail.com', 'Must be valid email format, unique', 0, '["Email Address", "Contact Email", "Login Email"]', '["player@example.com"]', 'Registration form', 'Provided by player at registration', '["email", "contact", "pii"]', 'Email Address', 'UNIQUE, EMAIL FORMAT', 0.95, 0.7, 'COUNT', '["Email", "Contact"]', 1, 0, 'System', GETUTCDATE()),

-- Demographics
(@PlayersTableId, 'Country', 'Player country of residence', 'Geographic location for compliance, marketing, and analytics. Links to jurisdiction rules.', 'United Kingdom, Germany, Canada', 'Must be valid country name', 0, '["Country", "Residence", "Location"]', '["United Kingdom", "Germany"]', 'Registration form or IP geolocation', 'Selected by player or detected', '["country", "geography", "compliance"]', 'Country Name', 'VARCHAR(50)', 0.9, 0.8, 'GROUP BY', '["Country", "Geography"]', 0, 0, 'System', GETUTCDATE()),

(@PlayersTableId, 'Currency', 'Player account currency', 'Base currency for all player transactions and balances', 'GBP, EUR, USD, CAD', 'Must be supported currency code', 0, '["Currency", "Account Currency", "Base Currency"]', '["GBP", "EUR", "USD"]', 'Registration form or country default', 'Selected by player or auto-assigned', '["currency", "financial"]', 'Currency Code', 'VARCHAR(10)', 0.98, 0.7, 'GROUP BY', '["Currency"]', 0, 0, 'System', GETUTCDATE()),

(@PlayersTableId, 'VIPLevel', 'Player VIP status level', 'Customer tier indicating value and privileges. Used for personalization and rewards.', 'Bronze, Silver, Gold, Platinum', 'Must be valid VIP level', 0, '["VIP Level", "Player Tier", "Customer Status"]', '["Bronze", "Silver", "Gold"]', 'VIP management system', 'Calculated based on activity and value', '["vip", "tier", "segmentation"]', 'VIP Level', 'VARCHAR(10)', 0.85, 0.6, 'GROUP BY', '["VIP Level", "Player Tier"]', 0, 1, 'System', GETUTCDATE()),

-- Financial Summary
(@PlayersTableId, 'Balance', 'Current account balance', 'Real money balance available for gaming. Critical for player experience.', '150.50, 0.00, 1000.00', 'Must be >= 0, in player currency', 0, '["Account Balance", "Available Balance", "Wallet Balance"]', '["150.50", "0.00", "1000.00"]', 'Real-time transaction processing', 'Deposits - Withdrawals - Bets + Wins', '["balance", "financial", "real_time"]', 'Currency Amount', '>= 0', 0.99, 0.8, 'SUM', '["Balance", "Wallet"]', 0, 1, 'System', GETUTCDATE()),

(@PlayersTableId, 'TotalDeposits', 'Lifetime total deposits', 'Sum of all successful deposits since registration. Key customer value metric.', '500.00, 2500.00, 10000.00', 'Must be >= 0, cumulative', 0, '["Total Deposits", "Lifetime Deposits", "Customer Value"]', '["500.00", "2500.00"]', 'Payment processing system', 'SUM of all successful deposits', '["deposit", "lifetime_value", "financial"]', 'Currency Amount', '>= 0', 0.98, 0.7, 'SUM', '["Total Deposits", "Customer Value"]', 0, 1, 'System', GETUTCDATE()),

-- Status and Compliance
(@PlayersTableId, 'IsActive', 'Player account active status', 'Indicates if player account is active and can perform transactions', '0, 1', 'Must be 0 or 1', 0, '["Active Status", "Account Status", "Enabled"]', '["0", "1"]', 'Account management system', 'Set based on account status rules', '["status", "active", "compliance"]', 'Boolean Flag', 'BIT (0 or 1)', 1.0, 0.6, 'COUNT', '["Active Status"]', 0, 0, 'System', GETUTCDATE());

PRINT '✅ tbl_Daily_actions_players column metadata populated (8 key columns)';

PRINT '';
PRINT '=== BUSINESS COLUMN METADATA POPULATION COMPLETE ===';
PRINT 'Successfully populated detailed column-level business metadata';
PRINT 'Tables processed: tbl_Daily_actions (12 columns), tbl_Daily_actions_players (8 columns)';
PRINT 'Total columns with business metadata: 20';
PRINT 'Column metadata includes: business meaning, context, examples, validation rules, semantic tags';
PRINT '';
