import React, { useState } from 'react';
import { Card, Button, Space, Typography, Tabs, Table, Tag, Alert, Statistic, Row, Col, Collapse, Badge, Modal, Descriptions, List, Input, Select, Form, message } from 'antd';
import { CheckCircleOutlined, TableOutlined, BookOutlined, ShareAltOutlined, EyeOutlined, DeleteOutlined, SaveOutlined, ColumnHeightOutlined, KeyOutlined, EditOutlined } from '@ant-design/icons';
import { AutoGenerationResponse, AutoGeneratedTableContext, AutoGeneratedGlossaryTerm } from '../../../services/tuningApi';

const { Title, Text, Paragraph } = Typography;
const { TabPane } = Tabs;
const { Panel } = Collapse;
const { TextArea } = Input;

interface AutoGenerationResultsProps {
  results: AutoGenerationResponse;
  onApply: (editedResults: AutoGenerationResponse) => void;
  onDiscard: () => void;
}

export const AutoGenerationResults: React.FC<AutoGenerationResultsProps> = ({
  results,
  onApply,
  onDiscard
}) => {
  const [editedResults, setEditedResults] = useState<AutoGenerationResponse>(results);
  const [selectedTableContext, setSelectedTableContext] = useState<AutoGeneratedTableContext | null>(null);
  const [selectedGlossaryTerm, setSelectedGlossaryTerm] = useState<AutoGeneratedGlossaryTerm | null>(null);
  const [tableModalVisible, setTableModalVisible] = useState(false);
  const [glossaryModalVisible, setGlossaryModalVisible] = useState(false);
  const [editingTableContext, setEditingTableContext] = useState<AutoGeneratedTableContext | null>(null);
  const [editingGlossaryTerm, setEditingGlossaryTerm] = useState<AutoGeneratedGlossaryTerm | null>(null);
  const [editTableModalVisible, setEditTableModalVisible] = useState(false);
  const [editGlossaryModalVisible, setEditGlossaryModalVisible] = useState(false);
  const [editingColumn, setEditingColumn] = useState<any>(null);
  const [editColumnModalVisible, setEditColumnModalVisible] = useState(false);
  const [editingTableForColumn, setEditingTableForColumn] = useState<AutoGeneratedTableContext | null>(null);
  const [form] = Form.useForm();
  const [columnForm] = Form.useForm();

  const getConfidenceColor = (score: number) => {
    if (score >= 0.8) return '#52c41a';
    if (score >= 0.6) return '#faad14';
    return '#ff4d4f';
  };

  const getConfidenceText = (score: number) => {
    if (score >= 0.8) return 'High';
    if (score >= 0.6) return 'Medium';
    return 'Low';
  };

  const handleViewTableDetails = (record: AutoGeneratedTableContext) => {
    setSelectedTableContext(record);
    setTableModalVisible(true);
  };

  const handleViewGlossaryDetails = (record: AutoGeneratedGlossaryTerm) => {
    setSelectedGlossaryTerm(record);
    setGlossaryModalVisible(true);
  };

  const handleEditTableContext = (record: AutoGeneratedTableContext) => {
    setEditingTableContext(record);
    form.setFieldsValue({
      businessPurpose: record.businessPurpose,
      businessContext: record.businessContext,
      primaryUseCase: record.primaryUseCase,
      businessRules: record.businessRules,
    });
    setEditTableModalVisible(true);
  };

  const handleEditGlossaryTerm = (record: AutoGeneratedGlossaryTerm) => {
    setEditingGlossaryTerm(record);
    form.setFieldsValue({
      term: record.term,
      definition: record.definition,
      category: record.category,
      businessContext: record.businessContext,
    });
    setEditGlossaryModalVisible(true);
  };

  const handleSaveTableEdit = async () => {
    try {
      const values = await form.validateFields();
      if (editingTableContext) {
        const updatedTableContext = {
          ...editingTableContext,
          ...values,
        };

        const updatedResults = {
          ...editedResults,
          generatedTableContexts: editedResults.generatedTableContexts.map(tc =>
            tc.tableName === editingTableContext.tableName && tc.schemaName === editingTableContext.schemaName
              ? updatedTableContext
              : tc
          ),
        };

        setEditedResults(updatedResults);
        setEditTableModalVisible(false);
        setEditingTableContext(null);
        form.resetFields();
        message.success('Table context updated successfully');
      }
    } catch (error) {
      console.error('Validation failed:', error);
    }
  };

  const handleSaveGlossaryEdit = async () => {
    try {
      const values = await form.validateFields();
      if (editingGlossaryTerm) {
        const updatedGlossaryTerm = {
          ...editingGlossaryTerm,
          ...values,
        };

        const updatedResults = {
          ...editedResults,
          generatedGlossaryTerms: editedResults.generatedGlossaryTerms.map(gt =>
            gt.term === editingGlossaryTerm.term ? updatedGlossaryTerm : gt
          ),
        };

        setEditedResults(updatedResults);
        setEditGlossaryModalVisible(false);
        setEditingGlossaryTerm(null);
        form.resetFields();
        message.success('Glossary term updated successfully');
      }
    } catch (error) {
      console.error('Validation failed:', error);
    }
  };

  const handleDeleteTableContext = (record: AutoGeneratedTableContext) => {
    const updatedResults = {
      ...editedResults,
      generatedTableContexts: editedResults.generatedTableContexts.filter(tc =>
        !(tc.tableName === record.tableName && tc.schemaName === record.schemaName)
      ),
    };
    setEditedResults(updatedResults);
    message.success('Table context removed');
  };

  const handleDeleteGlossaryTerm = (record: AutoGeneratedGlossaryTerm) => {
    const updatedResults = {
      ...editedResults,
      generatedGlossaryTerms: editedResults.generatedGlossaryTerms.filter(gt =>
        gt.term !== record.term
      ),
    };
    setEditedResults(updatedResults);
    message.success('Glossary term removed');
  };

  const handleEditColumn = (column: any, tableContext: AutoGeneratedTableContext) => {
    setEditingColumn(column);
    setEditingTableForColumn(tableContext);
    columnForm.setFieldsValue({
      businessDescription: column.businessDescription,
      businessDataType: column.businessDataType,
      businessContext: column.businessContext || '',
    });
    setEditColumnModalVisible(true);
  };

  const handleSaveColumnEdit = async () => {
    try {
      const values = await columnForm.validateFields();
      if (editingColumn && editingTableForColumn) {
        const updatedColumn = {
          ...editingColumn,
          ...values,
        };

        const updatedTableContext = {
          ...editingTableForColumn,
          columns: editingTableForColumn.columns.map(col =>
            col.columnName === editingColumn.columnName ? updatedColumn : col
          ),
        };

        const updatedResults = {
          ...editedResults,
          generatedTableContexts: editedResults.generatedTableContexts.map(tc =>
            tc.tableName === editingTableForColumn.tableName && tc.schemaName === editingTableForColumn.schemaName
              ? updatedTableContext
              : tc
          ),
        };

        setEditedResults(updatedResults);

        // Update the selected table context if it's currently being viewed
        if (selectedTableContext &&
            selectedTableContext.tableName === editingTableForColumn.tableName &&
            selectedTableContext.schemaName === editingTableForColumn.schemaName) {
          setSelectedTableContext(updatedTableContext);
        }

        // Update the editing table context if it's currently being edited
        if (editingTableContext &&
            editingTableContext.tableName === editingTableForColumn.tableName &&
            editingTableContext.schemaName === editingTableForColumn.schemaName) {
          setEditingTableContext(updatedTableContext);
        }

        setEditColumnModalVisible(false);
        setEditingColumn(null);
        setEditingTableForColumn(null);
        columnForm.resetFields();
        message.success('Column information updated successfully');
      }
    } catch (error) {
      console.error('Validation failed:', error);
    }
  };

  const tableContextColumns = [
    {
      title: 'Table',
      dataIndex: 'tableName',
      key: 'tableName',
      render: (text: string, record: AutoGeneratedTableContext) => (
        <Space>
          <TableOutlined />
          <Text strong>{record.schemaName}.{text}</Text>
        </Space>
      ),
    },
    {
      title: 'Business Purpose',
      dataIndex: 'businessPurpose',
      key: 'businessPurpose',
      ellipsis: true,
      width: 300,
    },
    {
      title: 'Columns',
      dataIndex: 'columns',
      key: 'columns',
      render: (columns: any[]) => (
        <Text>{columns.length} columns</Text>
      ),
    },
    {
      title: 'Confidence',
      dataIndex: 'confidenceScore',
      key: 'confidenceScore',
      render: (score: number) => (
        <Tag color={getConfidenceColor(score)}>
          {getConfidenceText(score)} ({Math.round(score * 100)}%)
        </Tag>
      ),
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (record: AutoGeneratedTableContext) => (
        <Space direction="vertical" size="small">
          <Space>
            <Button
              type="link"
              icon={<EyeOutlined />}
              onClick={() => handleViewTableDetails(record)}
              size="small"
            >
              View
            </Button>
            <Button
              type="link"
              icon={<EditOutlined />}
              onClick={() => handleEditTableContext(record)}
              size="small"
            >
              Edit
            </Button>
            <Button
              type="link"
              icon={<DeleteOutlined />}
              onClick={() => handleDeleteTableContext(record)}
              size="small"
              danger
            >
              Remove
            </Button>
          </Space>
          <Text type="secondary" style={{ fontSize: '11px' }}>
            {record.columns.length} columns
          </Text>
        </Space>
      ),
    },
  ];

  const glossaryTermColumns = [
    {
      title: 'Term',
      dataIndex: 'term',
      key: 'term',
      render: (text: string) => (
        <Space>
          <BookOutlined />
          <Text strong>{text}</Text>
        </Space>
      ),
    },
    {
      title: 'Definition',
      dataIndex: 'definition',
      key: 'definition',
      ellipsis: true,
      width: 300,
    },
    {
      title: 'Category',
      dataIndex: 'category',
      key: 'category',
      render: (category: string) => (
        <Tag>{category}</Tag>
      ),
    },
    {
      title: 'Sources',
      key: 'sources',
      render: (record: AutoGeneratedGlossaryTerm) => (
        <Text>{record.sourceTables.length + record.sourceColumns.length} sources</Text>
      ),
    },
    {
      title: 'Confidence',
      dataIndex: 'confidenceScore',
      key: 'confidenceScore',
      render: (score: number) => (
        <Tag color={getConfidenceColor(score)}>
          {getConfidenceText(score)} ({Math.round(score * 100)}%)
        </Tag>
      ),
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (record: AutoGeneratedGlossaryTerm) => (
        <Space>
          <Button
            type="link"
            icon={<EyeOutlined />}
            onClick={() => handleViewGlossaryDetails(record)}
            size="small"
          >
            View
          </Button>
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={() => handleEditGlossaryTerm(record)}
            size="small"
          >
            Edit
          </Button>
          <Button
            type="link"
            icon={<DeleteOutlined />}
            onClick={() => handleDeleteGlossaryTerm(record)}
            size="small"
            danger
          >
            Remove
          </Button>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <Card style={{ marginBottom: '24px' }}>
        <div style={{ marginBottom: '24px' }}>
          <Title level={4}>
            <CheckCircleOutlined style={{ marginRight: '8px', color: '#52c41a' }} />
            Auto-Generation Results
          </Title>
          <Paragraph type="secondary">
            Review the auto-generated business context below. You can examine each item in detail
            and then choose to apply all results or discard them.
          </Paragraph>
        </div>

        {/* Summary Statistics */}
        <Row gutter={16} style={{ marginBottom: '24px' }}>
          <Col span={6}>
            <Statistic
              title="Tables Processed"
              value={editedResults.generatedTableContexts.length}
              prefix={<TableOutlined />}
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="Columns Analyzed"
              value={results.totalColumnsProcessed}
              prefix={<ShareAltOutlined />}
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="Glossary Terms"
              value={editedResults.generatedGlossaryTerms.length}
              prefix={<BookOutlined />}
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="Processing Time"
              value={results.processingTime}
              suffix="ms"
            />
          </Col>
        </Row>

        {/* Warnings and Errors */}
        {results.warnings.length > 0 && (
          <Alert
            message="Warnings"
            description={
              <ul>
                {results.warnings.map((warning, index) => (
                  <li key={index}>{warning}</li>
                ))}
              </ul>
            }
            type="warning"
            showIcon
            style={{ marginBottom: '16px' }}
          />
        )}

        {results.errors.length > 0 && (
          <Alert
            message="Errors"
            description={
              <ul>
                {results.errors.map((error, index) => (
                  <li key={index}>{error}</li>
                ))}
              </ul>
            }
            type="error"
            showIcon
            style={{ marginBottom: '16px' }}
          />
        )}

        {/* Results Tabs */}
        <Tabs defaultActiveKey="tables" className="auto-generation-results-tabs">
          <TabPane
            tab={
              <Badge count={editedResults.generatedTableContexts.length} showZero>
                <Space>
                  <TableOutlined />
                  Table Contexts
                </Space>
              </Badge>
            }
            key="tables"
          >
            <Table
              dataSource={editedResults.generatedTableContexts}
              columns={tableContextColumns}
              rowKey={(record) => `${record.schemaName}.${record.tableName}`}
              pagination={{ pageSize: 10 }}
              size="small"
            />
          </TabPane>

          <TabPane
            tab={
              <Badge count={editedResults.generatedGlossaryTerms.length} showZero>
                <Space>
                  <BookOutlined />
                  Glossary Terms
                </Space>
              </Badge>
            }
            key="glossary"
          >
            <Table
              dataSource={editedResults.generatedGlossaryTerms}
              columns={glossaryTermColumns}
              rowKey="term"
              pagination={{ pageSize: 10 }}
              size="small"
            />
          </TabPane>

          {results.relationshipAnalysis && (
            <TabPane
              tab={
                <Badge count={results.relationshipAnalysis.relationships.length} showZero>
                  <Space>
                    <ShareAltOutlined />
                    Relationships
                  </Space>
                </Badge>
              }
              key="relationships"
            >
              <Collapse>
                <Panel header="Business Domains" key="domains">
                  {results.relationshipAnalysis.businessDomains.map((domain, index) => (
                    <Card key={index} size="small" style={{ marginBottom: '8px' }}>
                      <Title level={5}>{domain.domainName}</Title>
                      <Paragraph>{domain.description}</Paragraph>
                      <Space wrap>
                        {domain.tables.map((table, tableIndex) => (
                          <Tag key={tableIndex}>{table}</Tag>
                        ))}
                      </Space>
                    </Card>
                  ))}
                </Panel>

                <Panel header="Table Relationships" key="relationships">
                  {results.relationshipAnalysis.relationships.map((rel, index) => (
                    <Card key={index} size="small" style={{ marginBottom: '8px' }}>
                      <Text strong>
                        {rel.fromSchema}.{rel.fromTable} → {rel.toSchema}.{rel.toTable}
                      </Text>
                      <br />
                      <Text type="secondary">{rel.businessRelationship}</Text>
                      <br />
                      <Tag color={getConfidenceColor(rel.confidenceScore)}>
                        {Math.round(rel.confidenceScore * 100)}% confidence
                      </Tag>
                    </Card>
                  ))}
                </Panel>
              </Collapse>
            </TabPane>
          )}
        </Tabs>

        {/* Action Buttons */}
        <div style={{ marginTop: '24px', textAlign: 'center' }}>
          <Space size="large">
            <Button
              type="default"
              icon={<DeleteOutlined />}
              onClick={onDiscard}
              size="large"
            >
              Discard Results
            </Button>
            <Button
              type="primary"
              icon={<SaveOutlined />}
              onClick={() => onApply(editedResults)}
              size="large"
            >
              Apply All Results
            </Button>
          </Space>
        </div>

        <div style={{ marginTop: '16px', textAlign: 'center' }}>
          <Text type="secondary" style={{ fontSize: '12px' }}>
            Applying results will add the auto-generated content to your business context database.
            <br />
            You can always edit or remove individual items later through the respective management tabs.
          </Text>
        </div>
      </Card>

      {/* Table Details Modal */}
      <Modal
        title={
          selectedTableContext ? (
            <Space>
              <TableOutlined />
              <span>{selectedTableContext.schemaName}.{selectedTableContext.tableName}</span>
              <Tag color={getConfidenceColor(selectedTableContext.confidenceScore)}>
                {getConfidenceText(selectedTableContext.confidenceScore)} Confidence
              </Tag>
            </Space>
          ) : 'Table Details'
        }
        open={tableModalVisible}
        onCancel={() => setTableModalVisible(false)}
        footer={[
          <Button key="close" onClick={() => setTableModalVisible(false)}>
            Close
          </Button>
        ]}
        width={800}
      >
        {selectedTableContext && (
          <div>
            <Descriptions bordered column={1} size="small">
              <Descriptions.Item label="Business Purpose">
                {selectedTableContext.businessPurpose}
              </Descriptions.Item>
              <Descriptions.Item label="Business Context">
                {selectedTableContext.businessContext}
              </Descriptions.Item>
              <Descriptions.Item label="Primary Use Case">
                {selectedTableContext.primaryUseCase}
              </Descriptions.Item>
              <Descriptions.Item label="Business Rules">
                {selectedTableContext.businessRules}
              </Descriptions.Item>
              <Descriptions.Item label="Generation Method">
                {selectedTableContext.generationMethod}
              </Descriptions.Item>
              <Descriptions.Item label="Generated At">
                {new Date(selectedTableContext.generatedAt).toLocaleString()}
              </Descriptions.Item>
              <Descriptions.Item label="Confidence Score">
                <Tag color={getConfidenceColor(selectedTableContext.confidenceScore)}>
                  {Math.round(selectedTableContext.confidenceScore * 100)}%
                </Tag>
              </Descriptions.Item>
            </Descriptions>

            {selectedTableContext.keyBusinessMetrics.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Key Business Metrics</Title>
                <Space wrap>
                  {selectedTableContext.keyBusinessMetrics.map((metric, index) => (
                    <Tag key={index} color="blue">{metric}</Tag>
                  ))}
                </Space>
              </div>
            )}

            {selectedTableContext.commonQueryPatterns.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Common Query Patterns</Title>
                <Space wrap>
                  {selectedTableContext.commonQueryPatterns.map((pattern, index) => (
                    <Tag key={index} color="green">{pattern}</Tag>
                  ))}
                </Space>
              </div>
            )}

            {selectedTableContext.columns.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>
                  <ColumnHeightOutlined /> Column Information ({selectedTableContext.columns.length} columns)
                </Title>
                <List
                  size="small"
                  dataSource={selectedTableContext.columns}
                  renderItem={(column) => (
                    <List.Item>
                      <List.Item.Meta
                        avatar={column.isPrimaryKey ? <KeyOutlined style={{ color: '#faad14' }} /> : <ColumnHeightOutlined />}
                        title={
                          <Space>
                            <Text strong>{column.columnName}</Text>
                            {column.isPrimaryKey && <Tag color="gold">Primary Key</Tag>}
                            {column.isForeignKey && <Tag color="purple">Foreign Key</Tag>}
                          </Space>
                        }
                        description={
                          <div>
                            <Text>{column.businessDescription}</Text>
                            <br />
                            <Text type="secondary" style={{ fontSize: '12px' }}>
                              Type: {column.dataType} | Business Type: {column.businessDataType}
                            </Text>
                            {column.businessContext && (
                              <>
                                <br />
                                <Text type="secondary" style={{ fontSize: '11px', fontStyle: 'italic' }}>
                                  Context: {column.businessContext}
                                </Text>
                              </>
                            )}
                          </div>
                        }
                      />
                    </List.Item>
                  )}
                />
                <div style={{ marginTop: '8px', textAlign: 'center' }}>
                  <Text type="secondary" style={{ fontSize: '12px' }}>
                    💡 To edit column information, use the "Edit" button in the table list
                  </Text>
                </div>
              </div>
            )}

            {selectedTableContext.relatedTables.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Related Tables</Title>
                <Space wrap>
                  {selectedTableContext.relatedTables.map((table, index) => (
                    <Tag key={index} color="cyan">{table}</Tag>
                  ))}
                </Space>
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* Glossary Term Details Modal */}
      <Modal
        title={
          selectedGlossaryTerm ? (
            <Space>
              <BookOutlined />
              <span>{selectedGlossaryTerm.term}</span>
              <Tag color={getConfidenceColor(selectedGlossaryTerm.confidenceScore)}>
                {getConfidenceText(selectedGlossaryTerm.confidenceScore)} Confidence
              </Tag>
            </Space>
          ) : 'Glossary Term Details'
        }
        open={glossaryModalVisible}
        onCancel={() => setGlossaryModalVisible(false)}
        footer={[
          <Button key="close" onClick={() => setGlossaryModalVisible(false)}>
            Close
          </Button>
        ]}
        width={700}
      >
        {selectedGlossaryTerm && (
          <div>
            <Descriptions bordered column={1} size="small">
              <Descriptions.Item label="Term">
                {selectedGlossaryTerm.term}
              </Descriptions.Item>
              <Descriptions.Item label="Definition">
                {selectedGlossaryTerm.definition}
              </Descriptions.Item>
              <Descriptions.Item label="Category">
                <Tag>{selectedGlossaryTerm.category}</Tag>
              </Descriptions.Item>
              <Descriptions.Item label="Business Context">
                {selectedGlossaryTerm.businessContext}
              </Descriptions.Item>
              <Descriptions.Item label="Confidence Score">
                <Tag color={getConfidenceColor(selectedGlossaryTerm.confidenceScore)}>
                  {Math.round(selectedGlossaryTerm.confidenceScore * 100)}%
                </Tag>
              </Descriptions.Item>
            </Descriptions>

            {selectedGlossaryTerm.sourceTables.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Source Tables</Title>
                <Space wrap>
                  {selectedGlossaryTerm.sourceTables.map((table, index) => (
                    <Tag key={index} color="blue" icon={<TableOutlined />}>{table}</Tag>
                  ))}
                </Space>
              </div>
            )}

            {selectedGlossaryTerm.sourceColumns.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Source Columns</Title>
                <Space wrap>
                  {selectedGlossaryTerm.sourceColumns.map((column, index) => (
                    <Tag key={index} color="green" icon={<ColumnHeightOutlined />}>{column}</Tag>
                  ))}
                </Space>
              </div>
            )}

            {selectedGlossaryTerm.synonyms.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Synonyms</Title>
                <Space wrap>
                  {selectedGlossaryTerm.synonyms.map((synonym, index) => (
                    <Tag key={index} color="orange">{synonym}</Tag>
                  ))}
                </Space>
              </div>
            )}

            {selectedGlossaryTerm.relatedTerms.length > 0 && (
              <div style={{ marginTop: '16px' }}>
                <Title level={5}>Related Terms</Title>
                <Space wrap>
                  {selectedGlossaryTerm.relatedTerms.map((term, index) => (
                    <Tag key={index} color="purple">{term}</Tag>
                  ))}
                </Space>
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* Edit Table Context Modal */}
      <Modal
        title={
          editingTableContext ? (
            <Space>
              <EditOutlined />
              <span>Edit {editingTableContext.schemaName}.{editingTableContext.tableName}</span>
            </Space>
          ) : 'Edit Table Context'
        }
        open={editTableModalVisible}
        onCancel={() => {
          setEditTableModalVisible(false);
          setEditingTableContext(null);
          form.resetFields();
        }}
        footer={[
          <Button key="cancel" onClick={() => {
            setEditTableModalVisible(false);
            setEditingTableContext(null);
            form.resetFields();
          }}>
            Cancel
          </Button>,
          <Button key="save" type="primary" onClick={handleSaveTableEdit}>
            Save Changes
          </Button>
        ]}
        width={1000}
      >
        <Form form={form} layout="vertical">
          <Form.Item
            name="businessPurpose"
            label="Business Purpose"
            rules={[{ required: true, message: 'Please enter business purpose' }]}
          >
            <TextArea rows={3} placeholder="Describe the business purpose of this table..." />
          </Form.Item>

          <Form.Item
            name="businessContext"
            label="Business Context"
            rules={[{ required: true, message: 'Please enter business context' }]}
          >
            <TextArea rows={4} placeholder="Provide detailed business context..." />
          </Form.Item>

          <Form.Item
            name="primaryUseCase"
            label="Primary Use Case"
            rules={[{ required: true, message: 'Please enter primary use case' }]}
          >
            <TextArea rows={3} placeholder="Describe the primary use case..." />
          </Form.Item>

          <Form.Item
            name="businessRules"
            label="Business Rules"
          >
            <TextArea rows={3} placeholder="Enter any business rules or constraints..." />
          </Form.Item>
        </Form>

        {/* Column Editing Section */}
        {editingTableContext && editingTableContext.columns.length > 0 && (
          <div style={{ marginTop: '24px' }}>
            <Title level={5}>
              <ColumnHeightOutlined /> Edit Column Information ({editingTableContext.columns.length} columns)
            </Title>
            <List
              size="small"
              dataSource={editingTableContext.columns}
              renderItem={(column) => (
                <List.Item
                  actions={[
                    <Button
                      key="edit"
                      type="link"
                      icon={<EditOutlined />}
                      onClick={() => handleEditColumn(column, editingTableContext)}
                      size="small"
                    >
                      Edit Column
                    </Button>
                  ]}
                >
                  <List.Item.Meta
                    avatar={column.isPrimaryKey ? <KeyOutlined style={{ color: '#faad14' }} /> : <ColumnHeightOutlined />}
                    title={
                      <Space>
                        <Text strong>{column.columnName}</Text>
                        {column.isPrimaryKey && <Tag color="gold">Primary Key</Tag>}
                        {column.isForeignKey && <Tag color="purple">Foreign Key</Tag>}
                      </Space>
                    }
                    description={
                      <div>
                        <Text>{column.businessDescription}</Text>
                        <br />
                        <Text type="secondary" style={{ fontSize: '12px' }}>
                          Type: {column.dataType} | Business Type: {column.businessDataType}
                        </Text>
                        {column.businessContext && (
                          <>
                            <br />
                            <Text type="secondary" style={{ fontSize: '11px', fontStyle: 'italic' }}>
                              Context: {column.businessContext}
                            </Text>
                          </>
                        )}
                      </div>
                    }
                  />
                </List.Item>
              )}
            />
          </div>
        )}
      </Modal>

      {/* Edit Glossary Term Modal */}
      <Modal
        title={
          editingGlossaryTerm ? (
            <Space>
              <EditOutlined />
              <span>Edit {editingGlossaryTerm.term}</span>
            </Space>
          ) : 'Edit Glossary Term'
        }
        open={editGlossaryModalVisible}
        onCancel={() => {
          setEditGlossaryModalVisible(false);
          setEditingGlossaryTerm(null);
          form.resetFields();
        }}
        footer={[
          <Button key="cancel" onClick={() => {
            setEditGlossaryModalVisible(false);
            setEditingGlossaryTerm(null);
            form.resetFields();
          }}>
            Cancel
          </Button>,
          <Button key="save" type="primary" onClick={handleSaveGlossaryEdit}>
            Save Changes
          </Button>
        ]}
        width={700}
      >
        <Form form={form} layout="vertical">
          <Form.Item
            name="term"
            label="Term"
            rules={[{ required: true, message: 'Please enter the term' }]}
          >
            <Input placeholder="Enter the business term..." />
          </Form.Item>

          <Form.Item
            name="definition"
            label="Definition"
            rules={[{ required: true, message: 'Please enter definition' }]}
          >
            <TextArea rows={3} placeholder="Define what this term means..." />
          </Form.Item>

          <Form.Item
            name="category"
            label="Category"
            rules={[{ required: true, message: 'Please select a category' }]}
          >
            <Select placeholder="Select category">
              <Select.Option value="Financial">Financial</Select.Option>
              <Select.Option value="Gaming">Gaming</Select.Option>
              <Select.Option value="Player">Player</Select.Option>
              <Select.Option value="Transaction">Transaction</Select.Option>
              <Select.Option value="Reporting">Reporting</Select.Option>
              <Select.Option value="System">System</Select.Option>
              <Select.Option value="Other">Other</Select.Option>
            </Select>
          </Form.Item>

          <Form.Item
            name="businessContext"
            label="Business Context"
          >
            <TextArea rows={3} placeholder="Provide additional business context..." />
          </Form.Item>
        </Form>
      </Modal>

      {/* Edit Column Modal */}
      <Modal
        title={
          editingColumn ? (
            <Space>
              <EditOutlined />
              <span>Edit Column: {editingColumn.columnName}</span>
              <Tag color="blue">{editingColumn.dataType}</Tag>
            </Space>
          ) : 'Edit Column'
        }
        open={editColumnModalVisible}
        onCancel={() => {
          setEditColumnModalVisible(false);
          setEditingColumn(null);
          setEditingTableForColumn(null);
          columnForm.resetFields();
        }}
        footer={[
          <Button key="cancel" onClick={() => {
            setEditColumnModalVisible(false);
            setEditingColumn(null);
            setEditingTableForColumn(null);
            columnForm.resetFields();
          }}>
            Cancel
          </Button>,
          <Button key="save" type="primary" onClick={handleSaveColumnEdit}>
            Save Changes
          </Button>
        ]}
        width={600}
      >
        {editingColumn && (
          <div>
            <div style={{ marginBottom: '16px', padding: '12px', backgroundColor: '#f6f8fa', borderRadius: '6px' }}>
              <Text strong>Column: </Text>
              <Text code>{editingColumn.columnName}</Text>
              <br />
              <Text strong>Data Type: </Text>
              <Text>{editingColumn.dataType}</Text>
              <br />
              <Text strong>Table: </Text>
              <Text>{editingTableForColumn?.schemaName}.{editingTableForColumn?.tableName}</Text>
            </div>

            <Form form={columnForm} layout="vertical">
              <Form.Item
                name="businessDescription"
                label="Business Description"
                rules={[{ required: true, message: 'Please enter business description' }]}
              >
                <TextArea
                  rows={3}
                  placeholder="Describe what this column represents in business terms..."
                />
              </Form.Item>

              <Form.Item
                name="businessDataType"
                label="Business Data Type"
                rules={[{ required: true, message: 'Please select business data type' }]}
              >
                <Select placeholder="Select business data type">
                  <Select.Option value="Identifier">Identifier</Select.Option>
                  <Select.Option value="Amount">Amount</Select.Option>
                  <Select.Option value="Count">Count</Select.Option>
                  <Select.Option value="Date/Time">Date/Time</Select.Option>
                  <Select.Option value="Text">Text</Select.Option>
                  <Select.Option value="Flag">Flag</Select.Option>
                  <Select.Option value="Code">Code</Select.Option>
                  <Select.Option value="Percentage">Percentage</Select.Option>
                  <Select.Option value="Rate">Rate</Select.Option>
                  <Select.Option value="Status">Status</Select.Option>
                  <Select.Option value="Category">Category</Select.Option>
                  <Select.Option value="Other">Other</Select.Option>
                </Select>
              </Form.Item>

              <Form.Item
                name="businessContext"
                label="Business Context"
              >
                <TextArea
                  rows={2}
                  placeholder="Additional business context or usage notes..."
                />
              </Form.Item>
            </Form>
          </div>
        )}
      </Modal>
    </div>
  );
};
