-- Business Schema Management Tables
-- This migration adds comprehensive schema management with versioning

-- 1. Business Schemas (Main schema definitions)
CREATE TABLE BusinessSchemas (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500),
    CreatedBy NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedBy NVARCHAR(100) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsActive BIT NOT NULL DEFAULT 1,
    IsDefault BIT NOT NULL DEFAULT 0,
    Tags NVARCHAR(500), -- JSON array of tags
    CONSTRAINT UK_BusinessSchemas_Name UNIQUE (Name)
);

-- 2. Business Schema Versions (Version control)
CREATE TABLE BusinessSchemaVersions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SchemaId UNIQUEIDENTIFIER NOT NULL,
    VersionNumber INT NOT NULL,
    VersionName NVARCHAR(50), -- e.g., "v1.0", "Initial", "Q1-2024"
    Description NVARCHAR(1000),
    CreatedBy NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsActive BIT NOT NULL DEFAULT 1,
    IsCurrent BIT NOT NULL DEFAULT 0,
    ChangeLog NVARCHAR(MAX), -- JSON of changes made
    CONSTRAINT FK_BusinessSchemaVersions_Schema FOREIGN KEY (SchemaId) REFERENCES BusinessSchemas(Id) ON DELETE CASCADE,
    CONSTRAINT UK_BusinessSchemaVersions_SchemaVersion UNIQUE (SchemaId, VersionNumber)
);

-- 3. Schema Table Contexts (Business context for tables in each version)
CREATE TABLE SchemaTableContexts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SchemaVersionId UNIQUEIDENTIFIER NOT NULL,
    TableName NVARCHAR(128) NOT NULL,
    SchemaName NVARCHAR(128) NOT NULL DEFAULT 'dbo',
    BusinessPurpose NVARCHAR(500),
    BusinessContext NVARCHAR(MAX),
    PrimaryUseCase NVARCHAR(500),
    KeyBusinessMetrics NVARCHAR(MAX), -- JSON array
    CommonQueryPatterns NVARCHAR(MAX), -- JSON array
    BusinessRules NVARCHAR(MAX), -- JSON array
    ConfidenceScore DECIMAL(3,2),
    IsAutoGenerated BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_SchemaTableContexts_Version FOREIGN KEY (SchemaVersionId) REFERENCES BusinessSchemaVersions(Id) ON DELETE CASCADE,
    CONSTRAINT UK_SchemaTableContexts_VersionTable UNIQUE (SchemaVersionId, SchemaName, TableName)
);

-- 4. Schema Column Contexts (Business context for columns in each version)
CREATE TABLE SchemaColumnContexts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TableContextId UNIQUEIDENTIFIER NOT NULL,
    ColumnName NVARCHAR(128) NOT NULL,
    BusinessName NVARCHAR(200),
    BusinessDescription NVARCHAR(1000),
    BusinessDataType NVARCHAR(50),
    DataExamples NVARCHAR(MAX), -- JSON array
    ValidationRules NVARCHAR(MAX), -- JSON array
    CommonUseCases NVARCHAR(MAX), -- JSON array
    IsKeyColumn BIT NOT NULL DEFAULT 0,
    IsPrimaryKey BIT NOT NULL DEFAULT 0,
    IsForeignKey BIT NOT NULL DEFAULT 0,
    ConfidenceScore DECIMAL(3,2),
    IsAutoGenerated BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_SchemaColumnContexts_Table FOREIGN KEY (TableContextId) REFERENCES SchemaTableContexts(Id) ON DELETE CASCADE,
    CONSTRAINT UK_SchemaColumnContexts_TableColumn UNIQUE (TableContextId, ColumnName)
);

-- 5. Schema Glossary Terms (Business glossary for each version)
CREATE TABLE SchemaGlossaryTerms (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SchemaVersionId UNIQUEIDENTIFIER NOT NULL,
    Term NVARCHAR(200) NOT NULL,
    Definition NVARCHAR(MAX) NOT NULL,
    BusinessContext NVARCHAR(1000),
    Category NVARCHAR(100),
    Synonyms NVARCHAR(MAX), -- JSON array
    RelatedTerms NVARCHAR(MAX), -- JSON array
    SourceTables NVARCHAR(MAX), -- JSON array of table names
    SourceColumns NVARCHAR(MAX), -- JSON array of column names
    ConfidenceScore DECIMAL(3,2),
    IsAutoGenerated BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_SchemaGlossaryTerms_Version FOREIGN KEY (SchemaVersionId) REFERENCES BusinessSchemaVersions(Id) ON DELETE CASCADE,
    CONSTRAINT UK_SchemaGlossaryTerms_VersionTerm UNIQUE (SchemaVersionId, Term)
);

-- 6. Schema Relationships (Table relationships for each version)
CREATE TABLE SchemaRelationships (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SchemaVersionId UNIQUEIDENTIFIER NOT NULL,
    FromTable NVARCHAR(256) NOT NULL, -- schema.table
    ToTable NVARCHAR(256) NOT NULL, -- schema.table
    RelationshipType NVARCHAR(50) NOT NULL, -- FK, OneToMany, ManyToMany, etc.
    FromColumns NVARCHAR(MAX), -- JSON array
    ToColumns NVARCHAR(MAX), -- JSON array
    BusinessDescription NVARCHAR(1000),
    ConfidenceScore DECIMAL(3,2),
    IsAutoGenerated BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_SchemaRelationships_Version FOREIGN KEY (SchemaVersionId) REFERENCES BusinessSchemaVersions(Id) ON DELETE CASCADE
);

-- 7. User Schema Preferences (Which schema each user prefers for AI queries)
CREATE TABLE UserSchemaPreferences (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId NVARCHAR(100) NOT NULL,
    SchemaVersionId UNIQUEIDENTIFIER NOT NULL,
    IsDefault BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_UserSchemaPreferences_Version FOREIGN KEY (SchemaVersionId) REFERENCES BusinessSchemaVersions(Id) ON DELETE CASCADE,
    CONSTRAINT UK_UserSchemaPreferences_User UNIQUE (UserId, SchemaVersionId)
);

-- Create indexes for performance
CREATE INDEX IX_BusinessSchemas_IsActive ON BusinessSchemas(IsActive);
CREATE INDEX IX_BusinessSchemas_IsDefault ON BusinessSchemas(IsDefault);
CREATE INDEX IX_BusinessSchemaVersions_SchemaId_IsCurrent ON BusinessSchemaVersions(SchemaId, IsCurrent);
CREATE INDEX IX_SchemaTableContexts_SchemaVersionId ON SchemaTableContexts(SchemaVersionId);
CREATE INDEX IX_SchemaColumnContexts_TableContextId ON SchemaColumnContexts(TableContextId);
CREATE INDEX IX_SchemaGlossaryTerms_SchemaVersionId ON SchemaGlossaryTerms(SchemaVersionId);
CREATE INDEX IX_SchemaRelationships_SchemaVersionId ON SchemaRelationships(SchemaVersionId);
CREATE INDEX IX_UserSchemaPreferences_UserId ON UserSchemaPreferences(UserId);

-- Insert default schema
INSERT INTO BusinessSchemas (Name, Description, CreatedBy, UpdatedBy, IsDefault)
VALUES ('Default Schema', 'Default business context schema', 'System', 'System', 1);

DECLARE @DefaultSchemaId UNIQUEIDENTIFIER = (SELECT Id FROM BusinessSchemas WHERE Name = 'Default Schema');

INSERT INTO BusinessSchemaVersions (SchemaId, VersionNumber, VersionName, Description, CreatedBy, IsCurrent)
VALUES (@DefaultSchemaId, 1, 'v1.0', 'Initial default schema version', 'System', 1);
